<?php

/**
 * PluginIntroFriendUnreadTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginIntroFriendUnreadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginIntroFriendUnreadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginIntroFriendUnread');
    }
}
