<?php

/**
 * PluginIntroFriendUnread
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginIntroFriendUnread extends BaseIntroFriendUnread
{
  public function increaseCount()
  {
    $this->set('count', ($this->getCount() + 1));
  }

  public function decreaseCount()
  {
    $count = $this->getCount() - 1;
    if ($count <= 0) $count = 0;
    $this->set('count', $count);
  }

  public function doRead()
  {
    $dateTime = new DateTime();
    $this->set('count', 0);
    $this->setReadAt($dateTime->format('Y-m-d H:i:s'));
    $this->save();
  }


}
